### ISSUE TITLE
Nothing for Linux and Firefox?

### ISSUE THREAD

**Issue by DarkGuy10** [DarkKnight450/BingWallpaperDownloader#2]
Would love to see a version for Linux and Firefox, and DuckDuckGo, XD

**Comment by BillyDoesDev** [comment]
@DarkGuy10 ya sure...

**Comment by DarkGuy10** [comment]
You know what, we can create a bash only version for linux, using wget / curl

**Comment by BillyDoesDev** [comment]
@DarkGuy10 I don't think so, cuz the download links are dynamic, i.e. they change everyday...

      The way my program works is that it looks for the element containing the download link and then fetches the file...

**Comment by DarkGuy10** [comment]
Hey bruh, I successfully made the script
And it schedules itself to run everyday
U wannit?

**Comment by DarkGuy10** [comment]
bash script
